# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
  - script: |
      mkdir C:\buildtesting

      copy wpiutild.dll C:\buildtesting\wpiutild.dll
      copy wpiutiljni.dll C:\buildtesting\wpiutiljni.dll
      copy Program.java C:\buildtesting\Program.java

      C:

      cd C:\buildtesting

      "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" -i wpiutild.dll +sls
      "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" -i wpiutiljni.dll +sls
      "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" -i "C:\Program Files\Java\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64\bin\java.exe" +sls

      "C:\Program Files\Java\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64\bin\javac.exe" Program.java

      "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe" -g -G -x "C:\Program Files\Java\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64\bin\java.exe" "-Djava.library.path=." Program
    condition: always()
