# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
  - script: |
      echo %PATH%
    condition: always()
  - script: |
      echo %PATH%

      SET PATH=C:\windows\system32;C:\windows;

      echo %PATH%

      "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" -i wpiutild.dll +sls
      "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" -i NativeApp\LoadTest.exe +sls

      "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe" -g -G -x NativeApp\LoadTest.exe
    condition: always()
